"""Add user relationship to Reservation

Revision ID: 05892d00512c
Revises: a8cf32917fef
Create Date: 2024-11-15 22:54:55.163142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05892d00512c'
down_revision = 'a8cf32917fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
