"""Made a Donation model

Revision ID: 4a7079369811
Revises: eef665fd5a36
Create Date: 2024-11-15 18:08:28.278073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a7079369811'
down_revision = 'eef665fd5a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
