"""Add default value for fully invested fiels

Revision ID: 58d0e3f7d1a4
Revises: c1081e0521be
Create Date: 2024-11-29 20:25:17.536855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d0e3f7d1a4'
down_revision = 'c1081e0521be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
