"""Add project model

Revision ID: b925857f37b6
Revises: 41cabc928851
Create Date: 2024-11-12 22:40:12.707679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b925857f37b6'
down_revision = '41cabc928851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
